import '@/styles/globals.scss'
import type { AppProps } from 'next/app'
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-icons/font/bootstrap-icons.css'

import Header from '@/components/header'
import Footer from '@/components/footer'
import Head from 'next/head'
import PageLayout from '@/layout/pageLayout'
import { useEffect } from 'react'


export default function App({ Component, pageProps }: AppProps) {
  
  useEffect(() => {
    require("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);

  

  return <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header></Header>
    <PageLayout>
      <Component {...pageProps} />
    </PageLayout>
    <Footer></Footer>
  </>
}
